### ISSUE TITLE
Issue with mythic+ tracking

### ISSUE THREAD

**Issue by SoLoR1** [eTzmNcbkrng/SavedInstances#1]
Hey,

nice to see someone is trying to maintain this addon!

Having issue with mythic+ tracking:

177x SavedInstances\SavedInstances-@project-version@.lua:2865: attempt to compare number with nil
SavedInstances\SavedInstances-@project-version@.lua:2865: in function `?'
...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...dia\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

tryed with all addons disabled and it didnt go away... english client. i think issue starts with:

local KeyInfo = {strsplit(':', keyLink)}

but my knowledge what could be wrong ends there :)

**Comment by eTzmNcbkrng** [comment]
I can't believe I've figure this out!
It appears as though Blizzard changed the information that is stored inside a Keystone item link. I had to figure out what the new indexes were for various things.
I'm pretty terrible so my Keystone never gets to a particularly high level, hence I will not be able to test that the colours are correct. Mine is currently a +2 and is displaying as a white colour in the SI tooltip. If the colours are wrong for higher level ones it can be changed.

**Comment by SoLoR1** [comment]
Latest commit fixes issue! ty
