### ISSUE TITLE
[Request} New Seal of Fate purchased with Mark of Honor

### ISSUE THREAD

**Issue by angryindianman** [eTzmNcbkrng/SavedInstances#10]
Thanks again for updating this addon :)

Seal of Fate purchased with Mark of Honor is not calculated properly via weekly seal cap. I purchased 3 seal of fate this week, 2 with order resource and 1 with mark of honor. Weekly "purchasable" cap shows 2/3 tho it should be 3/3.
Also, the [Sealing Fate: Marks of Honor] quest is currently shown under Daily quests instead of Weekly Quests.

**Comment by ceylina** [comment]
ID are 47851, 47864, and 47865

So add after line 360:

  [47851] = "Weekly", -- mark of honor x5
  [47864] = "Weekly", -- mark of honor x10
  [47865] = "Weekly", -- mark of honor x20

**Comment by angryindianman** [comment]
Worked like a charm.
Thank you
