### ISSUE TITLE
Lua error on 7.2.5

### ISSUE THREAD

**Issue by Tykwer** [eTzmNcbkrng/SavedInstances#11]
Hi,

Thanks so much for maintaining this addon.  I am getting the following error as of 7.2.5 and was wondering if you would be willing to take a look at a fix.

Date: 2017-06-14 02:50:00
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 1816:
   attempt to index local 'texture' (a number value)
Debug:
   SavedInstances\SavedInstances.lua:1816: QuestIsDarkmoonMonthly()
   SavedInstances\SavedInstances.lua:1841:
      SavedInstances\SavedInstances.lua:1835
   [C]: GetQuestReward()
   ..\FrameXML\QuestFrame.lua:161:
      ..\FrameXML\QuestFrame.lua:147
Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1823
 GetServerOffset = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:773
 oi_cache = <table> {
 }
 questdebug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:401
 QuestInfo = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:333
 pvpdesertids = <table> {
 }
 icon = <table> {
 }
 histLiveCount = 0
 FindInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:981
 UpdateToonData = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1573
 GetRegion = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:789
 InGroup = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2830
 chatMsg = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:343
 CategorySize = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1068
 formatNumber = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:459
 GetNextDailyResetTime = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:814
 OrderedCategories = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1261
 instanceException = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1166
 db = <table> {
 }
 diff_strings = <table> {
 }
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 IsDetached = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3363
 config = <table> {
 }
 QuestIsDarkmoonMonthly = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1809
 SkinFrame = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:687
 Categories = <table> {
 }
 histTextUpdate = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3034
 HistoryEvent = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2865
 SetupVersion = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2606
 InstanceCategory = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1048
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3366
 currency_sort = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2477
 updatetooltip_throttle = 0.26700001396239
 UpdateInstanceData = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1360
 headerfont = SavedInstancedTooltipHeaderFont {
 }
 GetNextWeeklyResetTime = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:873
 WorldBosses = <table> {
 }
 revision = 550
 oc_cache = <table> {
 }
 region = "US"
 histOldest = "n/a"
 resetDays = <table> {
 }
 core = <table> {
 }
 activeHolidays = <table> {
 }
 LDB = <table> {
 }
 scaleCache = <table> {
 }
 PlayedTime = 1497433763
 UpdateInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1476
 delayUpdate = 1497433783
 debug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:347
 firstupdate = false
 LookupInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1017
 GetSeasonCurrency = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2375
 version = "7.0.8"
 idtext = <function> defined @Interface\AddOns\SavedInstances\config.lua:45
 Indicators = <table> {
 }
 UpdateCurrency = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1759
 OrderedInstances = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1248
 updateSpellTip = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1554
 currency = <table> {
 }
 normalizeName = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:955
 BonusRollShow = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:4754
 instancesUpdated = true
 L = <table> 
AddOns:

(truncated)

Thanks for your help!
Matt

**Comment by b-morgan** [comment]
I'm getting the same error.

**Comment by ceylina** [comment]
Search for 

if texture:find("_ticket_darkmoon_") then

replace it with

if texture == 134481 then 


This should fix the issue

Credit goes to

https://mods.curse.com/addons/wow/saved_instances?comment=818

**Comment by Tykwer** [comment]
Thank you very much =)
