### ISSUE TITLE
Tomb of Sargeras - fix in initial comment

### ISSUE THREAD

**Issue by ceylina** [eTzmNcbkrng/SavedInstances#13]
EDIT...

I am editing this initial comment to suggest changes to add in TOS

For LFR
After line 149.

  [1494] = { total=3, base=1, parent=1527,altid=nil }, -- TOS1: The Gates of Hell
  [1495] = { total=3, base=4, parent=1527,altid=nil, remap={ 1, 2, 3 } }, -- TOS2: Wailing Halls
  [1496] = { total=2, base=7, parent=1527,altid=nil, remap={ 1, 2} }, -- TOS3: Chamber of the Avatar
  [1497] = { total=1, base=9, parent=1527,altid=nil, remap={ 1 } }, -- TOS4: Deceiver's Fall 

This is based on the current information that wing 1 is 3 bosses, wing 2 is 3 bosses, wing 3 is 2 bosses, then kiljaeden is alone in the last wing. The remap may not be correct but it is my best educated guess.

To open TOS for normal and above change 

local maxid = 1500
to 
local maxid = 1700

TOS is instance ID 1676 so it needs to be above to include. 1700 should be the closest without risking possible errors.

**Comment by ceylina** [comment]
Ok I think the Id for the parent is 1676 if using GetInstanceInfo() is the right method.

SO...

If I did this right, it should be


[1494] = { total=3, base=1, parent=1676,altid=nil }, -- TOS1: The Gates of Hell
[1495] = { total=3, base=4, parent=1676,altid=nil, remap={ 1, 2, 3 } }, -- TOS2: Wailing Halls
[1496] = { total=2, base=7, parent=1676,altid=nil, remap={ 1, 2} }, -- TOS3: Chamber of the Avatar
[1497] = { total=1, base=9, parent=1676,altid=nil, remap={ 1 } }, -- TOS4: Deceiver's Fall

**Comment by caricatura** [comment]
According to the message i got today i believe the parent should be 1676
SavedInstances: SavedInstances: ERROR: Refresh() failed to find instance: Tomb of Sargeras : enUS : 1676

**Comment by ceylina** [comment]
How I was able to get the raid finder IDs was

/script local id,name; for i=1,GetNumRFDungeons() do id,name = GetRFDungeonInfo(i);print(i..". "..name.." ("..id..")");end

Which returns this

1. Fall of Deathwing (417)
2. The Siege of Wyrmrest Temple (416)
3. Darkbough (1287)
4. Guardians of Mogu'shan (527)
5. Walled City (849)
6. Arcane Sanctum (850)
7. The Vault of Mysteries (528)
8. Tormented Guardians (1288)
9. Imperator's Rise (851)
10. Rift of Aln (1289)
11. The Dread Approach (529)
12. Nightmare of Shek'zeer (530)
13. Slagworks (847)
14. Trial of Valor (1411)
15. Arcing Aqueducts (1290)
16. Terrace of Endless Spring (526)
17. The Black Forge (846)
18. Iron Assembly (848)
19. Last Stand of the Zandalari (610)
20. Royal Athenaeum (1291)
21. Blackhand's Crucible (823)
22. Forgotten Depths (611)
23. Nightspire (1292)
24. Betrayer's Rise (1293)
25. Halls of Flesh-Shaping (612)
26. Hellbreach (982)
27. Halls of Blood (983)
28. Pinnacle of Storms (613)
29. The Gates of Hell (1494)
30. Bastion of Shadows (984)
31. Vale of Eternal Sorrows (716)
32. Wailing Halls (1495)
33. Chamber of the Avatar (1496)
34. Destructor's Rise (985)
35. Gates of Retribution (717)
36. Deceiver's Fall (1497)
37. The Black Gate (986)
38. The Underhold (724)
39. Downfall (725)

Manually confirming that the 1400 IDs are tomb.

So all I need to know is what exactly is parent in the code and I can look up for tomb of sargeras.

**Comment by ceylina** [comment]
Using 

http://wow.gamepedia.com/API_GetLFRChoiceOrder

It seems either 1525, 1526, or 1527 is the parent id for tomb.

This is the dump of the following script

/run for i, v in ipairs(GetLFRChoiceOrder()) do print(i, v, GetLFGDungeonInfo(v)) end

1 -53 Legion Normal 1
2 -52 Legion Heroic 1
3 -48 Warlords of Draenor Heroic 1
4 -47 Warlords of Draenor Normal 1
5 -36 Mists of Pandaria Heroic 1
6 -37 Mists of Pandaria Normal 1
7 -33 Hour of Twilight Heroic 1
8 -12 Cataclysm Heroic 1
9 -13 Cataclysm Normal 1
10 -5 Wrath of the Lich King Heroic 1
11 -4 Wrath of the Lich King Normal 1
12 -3 Burning Crusade Heroic 1
13 -2 Burning Crusade Normal 1
14 -1 Classic Dungeons 1
15 -54 Legion Raid (Normal) 2
16 1348 The Emerald Nightmare 2 0 110 110 110 110 110 6 -54 nil 14 0  false 0 nil false The Emerald Nightmare 0
17 1351 The Nighthold 2 0 110 110 110 110 110 6 -54 nil 14 0  false 0 nil false The Nighthold 0
18 1525 Tomb of Sargeras 2 0 110 110 110 110 110 6 -54 nil 14 0  false 0 nil false Tomb of Sargeras 0
19 1437 Trial of Valor 2 0 110 110 110 110 110 6 -54 nil 14 0  false 0 nil false Trial of Valor 0
20 -55 Legion Raid (Heroic) 2
21 1349 The Emerald Nightmare 2 0 110 110 110 110 110 6 -55 nil 15 0  false 0 nil false The Emerald Nightmare 0
22 1352 The Nighthold 2 0 110 110 110 110 110 6 -55 nil 15 0  false 0 nil false The Nighthold 0
23 1526 Tomb of Sargeras 2 0 110 110 110 110 110 6 -55 nil 15 0  false 0 nil false Tomb of Sargeras 0
24 1439 Trial of Valor 2 0 110 110 110 110 110 6 -55 nil 15 0  false 0 nil false Trial of Valor 0
25 -56 Legion Raid (Mythic) 2
26 1350 The Emerald Nightmare 2 0 110 110 110 110 110 6 -56 nil 16 0  false 0 nil false The Emerald Nightmare 0
27 1353 The Nighthold 2 0 110 110 110 110 110 6 -56 nil 16 0  false 0 nil false The Nighthold 0
28 1527 Tomb of Sargeras 2 0 110 110 110 110 110 6 -56 nil 16 0  false 0 nil false Tomb of Sargeras 0
29 1438 Trial of Valor 2 0 110 110 110 110 110 6 -56 nil 16 0  false 0 nil false Trial of Valor 0
30 -49 Warlords of Draenor Raid (Normal) 2
31 898 Blackrock Foundry 2 0 100 100 100 100 100 5 -49 nil 14 0  false 0 nil false Blackrock Foundry 0
32 987 Hellfire Citadel 2 0 100 100 100 100 100 5 -49 nil 14 0  false 0 nil false Hellfire Citadel 0
33 895 Highmaul 2 0 100 100 100 100 100 5 -49 nil 14 0  false 0 nil false Highmaul 0
34 -50 Warlords of Draenor Raid (Heroic) 2
35 899 Blackrock Foundry 2 0 100 100 100 100 100 5 -50 nil 15 0  false 0 nil false Blackrock Foundry 0
36 988 Hellfire Citadel 2 0 100 100 100 100 100 5 -50 nil 15 0  false 0 nil false Hellfire Citadel 0
37 896 Highmaul 2 0 100 100 100 100 100 5 -50 nil 15 0  false 0 nil false Highmaul 0
38 -51 Warlords of Draenor Raid (Mythic) 2
39 900 Blackrock Foundry 2 0 100 100 100 100 100 5 -51 nil 16 0  false 0 nil false Blackrock Foundry 0
40 989 Hellfire Citadel 2 0 100 100 100 100 100 5 -51 nil 16 0  false 0 nil false Hellfire Citadel 0
41 897 Highmaul 2 0 100 100 100 100 100 5 -51 nil 16 0  false 0 nil false Highmaul 0
42 -46 Mists of Pandaria World Boss 2
43 768 Celestials 2 0 90 90 90 90 90 4 -46 nil 4 0  false 0 nil false Pandaria 0
44 767 Ordos 2 0 90 90 90 90 90 4 -46 nil 4 0  false 0 nil false Pandaria 0
45 -45 Mists of Pandaria Raid (Flex) 2
46 715 Siege of Orgrimmar 2 0 90 90 90 90 90 4 -45 nil 14 0  false 0 nil false Siege of Orgrimmar 0
47 766 Siege of Orgrimmar 2 0 90 90 90 90 90 4 -45 nil 16 0  false 0 nil false Siege of Orgrimmar 0
48 714 Siege of Orgrimmar 2 0 90 90 90 90 90 4 -45 nil 15 0  false 0 nil false Siege of Orgrimmar 0
49 -41 Mists of Pandaria Raid (10) 2
50 533 Heart of Fear 2 0 90 90 90 90 90 4 -41 nil 3 0  false 0 nil false Heart of Fear 0
51 531 Mogu'shan Vaults 2 0 90 90 90 90 90 4 -41 nil 3 0  false 0 nil false Mogu'shan Vaults 0
52 535 Terrace of Endless Spring 2 0 90 90 90 90 90 4 -41 nil 3 0  false 0 nil false Terrace of Endless Spring 0
53 633 Throne of Thunder 2 0 90 90 90 90 90 4 -41 nil 3 0  false 0 nil false Throne of Thunder 0
54 -40 Mists of Pandaria Raid (25) 2
55 534 Heart of Fear 2 0 90 90 90 90 90 4 -40 nil 4 0  false 0 nil false Heart of Fear 0
56 532 Mogu'shan Vaults 2 0 90 90 90 90 90 4 -40 nil 4 0  false 0 nil false Mogu'shan Vaults 0
57 536 Terrace of Endless Spring 2 0 90 90 90 90 90 4 -40 nil 4 0  false 0 nil false Terrace of Endless Spring 0
58 634 Throne of Thunder 2 0 90 90 90 90 90 4 -40 nil 4 0  false 0 nil false Throne of Thunder 0
59 -14 Cataclysm Raid (25) 2
60 329 Baradin Hold 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false Baradin Hold 329
61 314 Blackwing Descent 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false Blackwing Descent 342
62 448 Dragon Soul 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false Dragon Soul 365
63 362 Firelands 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false Firelands 355
64 316 The Bastion of Twilight 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false The Bastion of Twilight 342
65 318 Throne of the Four Winds 2 0 85 85 85 85 85 3 -14 nil 4 0  false 0 nil false Throne of the Four Winds 342
66 -15 Cataclysm Raid (10) 2
67 328 Baradin Hold 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false Baradin Hold 329
68 313 Blackwing Descent 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false Blackwing Descent 342
69 447 Dragon Soul 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false Dragon Soul 365
70 361 Firelands 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false Firelands 355
71 315 The Bastion of Twilight 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false The Bastion of Twilight 342
72 317 Throne of the Four Winds 2 0 85 85 85 85 85 3 -15 nil 3 0  false 0 nil false Throne of the Four Winds 342
73 -9 Wrath of the Lich King Raid (25) 2
74 280 Icecrown Citadel 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Icecrown Citadel 226
75 227 Naxxramas 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Naxxramas 187
76 257 Onyxia's Lair 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Onyxia's Lair 187
77 294 Ruby Sanctum 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false The Ruby Sanctum 219
78 237 The Eye of Eternity 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false The Eye of Eternity 187
79 238 The Obsidian Sanctum 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false The Obsidian Sanctum 187
80 248 Trial of the Crusader 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Trial of the Crusader 219
81 250 Trial of the Grand Crusader 2 0 80 83 80 80 83 2 -9 nil 6 0  false 0 nil false Trial of the Crusader 226
82 244 Ulduar 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Ulduar 200
83 240 Vault of Archavon 2 0 80 83 80 80 83 2 -9 nil 4 0  false 0 nil false Vault of Archavon 187
84 -8 Wrath of the Lich King Raid (10) 2
85 279 Icecrown Citadel 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Icecrown Citadel 219
86 159 Naxxramas 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Naxxramas 187
87 46 Onyxia's Lair 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Onyxia's Lair 187
88 293 Ruby Sanctum 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false The Ruby Sanctum 219
89 223 The Eye of Eternity 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false The Eye of Eternity 187
90 224 The Obsidian Sanctum 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false The Obsidian Sanctum 187
91 246 Trial of the Crusader 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Trial of the Crusader 200
92 247 Trial of the Grand Crusader 2 0 80 83 80 80 83 2 -8 nil 5 0  false 0 nil false Trial of the Crusader 213
93 243 Ulduar 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Ulduar 200
94 239 Vault of Archavon 2 0 80 83 80 80 83 2 -8 nil 3 0  false 0 nil false Vault of Archavon 187
95 -7 Burning Crusade Raid 2
96 196 Black Temple 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false Black Temple 0
97 177 Gruul's Lair 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false Gruul's Lair 0
98 195 Hyjal Past 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false The Battle for Mount Hyjal 0
99 175 Karazhan 2 0 70 70 70 70 70 1 -7 nil 3 0  false 0 nil false Karazhan 0
100 176 Magtheridon's Lair 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false Magtheridon's Lair 0
101 194 Serpentshrine Cavern 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false Coilfang: Serpentshrine Cavern 0
102 193 Tempest Keep 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false Tempest Keep 0
103 199 The Sunwell 2 0 70 70 70 70 70 1 -7 nil 4 0  false 0 nil false The Sunwell 0
104 -6 Classic Raid 2
105 160 Ahn'Qiraj Ruins 2 0 60 60 60 60 60 0 -6 nil 3 0  false 0 nil false Ruins of Ahn'Qiraj 0
106 161 Ahn'Qiraj Temple 2 0 60 60 60 60 60 0 -6 nil 9 0  false 0 nil false Ahn'Qiraj Temple 0
107 50 Blackwing Lair 2 0 60 60 60 60 60 0 -6 nil 9 0  false 0 nil false Blackwing Lair 0
108 48 Molten Core 2 0 60 60 60 60 60 0 -6 nil 9 0  false 0 nil false Molten Core 0
109 -11 World Events 0
110 -20 Rated Battleground 2
111 -38 Scenarios 1
112 -43 Heroic Scenarios 1
113 -44 Timewalking 0

**Comment by ceylina** [comment]
Only problem is I still am getting the following

[04:10:15] SavedInstances: SavedInstances: ERROR: Refresh() failed to find instance: Tomb of Sargeras : enUS : 1676
[04:10:15] SavedInstances: Please report this bug at: http://www.wowace.com/addons/saved_instances/tickets/

So what I am wondering is where else are you now saving normal and above raid instances?!

**Comment by AlexAtTheBux** [comment]
Found the fix for this...and its quite silly. SavedInstances is currently only grabbing instance data for instanceID's through 1500, and Tomb of Sargeras has ID's 1525, 1526, and 1527.  So the code is not even getting to those ID's. Line 1398 currently reads ```local maxid = 1500```.  Change that to 2000 (to avoid this issue in future patches), and everything works as expected.

The proper parentID for ToS should be 1527 to keep it in line with previous raids using the highest instanceID for the parent.

We won't know the proper remaps until all four LFR wings open. If you recall the remap issues with Nighthold, they were all initially not remaped, providing proper LFR appearance when Arcing Aqueducts (wing 1) opened.  However, when Royal Athenaeum (wing 2) opened, we had to remap wings 2-4 as ```{ 1, 2, 3 }```, ```{ 4, 5, 6 }```, and ```{ 7 }```. Then when Nightspire (wing 3) opened, we had to remap wings 3 and 4 as ```{ 1, 2, 3 }``` and ```{ 4 }```, and eventually remap Betrayer's Rise as ```{ 1 }```. Using ```remap = { 1, 2, 3 }``` *might* be correct eventually but it will likely display incorrectly until Deceiver's Fall is available on LFR, so for now we should just update the remaps as the wings are released.

**Comment by ceylina** [comment]
Thanks for finding that. I was trying to find this late last night and was tired lol. I think that id has to go to 1700 as the instance ID for tomb is actually 1676 but the lfr choice order is 1527 for the parentID

**Comment by ceylina** [comment]
One more thing. I think that maxid variable should be global to the addon and set at the top of the code so it is easily found and changed as more dungeons and raids are added. 1700 works for now to add tos

**Comment by AlexAtTheBux** [comment]
Where are you getting 1676 from? I'm not seeing that in any data dumps.  Regardless, 2000 or 1700 will work for ToS,   I do agree that maxid should be at the top, perhaps right below maxdiff and maxcol. I moved it below them as this:
```lua
local maxid = 1700 -- highest possible value for an instanceID, current max (Tomb of Sargeras) is 1676
```

**Comment by ceylina** [comment]
> [04:10:15] SavedInstances: SavedInstances: ERROR: Refresh() failed to find instance: Tomb of Sargeras : enUS : 1676

It's right form the error printout as well as actually going into the raid and dumping via 

/dump GetInstanceInfo()

I would assume you don't want to set maxID too far past the highest current raid ID to prevent the potential for taint or other errors to form.

**Comment by AlexAtTheBux** [comment]
Oh, ok.  I didn't do that dump while I was inside, but there isn't really any cause for taint from going too high as it'll just return ```nil``` values that get scrapped.

I uploaded a .zip on ticket #8 that includes the ToS fixes, as well as emissary and keystone fixes.  This fix goes to 2000, but you can adjust it down to 1700.

**Comment by ceylina** [comment]
Leave it to 2000. I bet there won't be an issue and if there is it can get adjusted as needed ;)
