### ISSUE TITLE
Possible Error in locale.lua

### ISSUE THREAD

**Issue by Tumbleweed64** [eTzmNcbkrng/SavedInstances#15]
Have had a look at the locale.lua and found a possible error in the brazillian language.
In line 1256 is a break:
```
La["Ignore"] = [=[Ignorar
]=]
```
I'm not sure that this break should be there, so please have a look at the line. :)

**Comment by AlexAtTheBux** [comment]
locale.lua will be reworked when I get home later. That line does look to be an error, but I'm not sure where it came from as I didn't add anything to locales besides enUS.

**Comment by Tumbleweed64** [comment]
I think its a simple error done by a wrong linebreak. :)

**Comment by Stanzilla** [comment]
Hey there, you can actually fix this yourself when you go to https://www.wowace.com/projects/saved_instances/localization and search for that string in your language, I assume it's Spanish/Portuguese? Thanks for reporting though!
