### ISSUE TITLE
Adding Writhing Essences

### ISSUE THREAD

**Issue by SiegaPlays** [eTzmNcbkrng/SavedInstances#16]
Writhing Essences are now a currency, to add to this addon add this line 103 in SavedINstances.lua
1501,-- Writhing Essence
it should then show in the options

(credit goes to [post from Zulinia from curse.com](https://mods.curse.com/addons/wow/saved_instances?comment=849))

**Comment by ceylina** [comment]
Actually with the latest branch it is line 131
