### ISSUE TITLE
Addon wont open anymore since last update

### ISSUE THREAD

**Issue by Akrolodoxis** [eTzmNcbkrng/SavedInstances#17]
Pretty long errorcode

4x SavedInstances\SavedInstances-@project-version@.lua:4193: attempt to concatenate local 'kabbrev' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:4193: in function `ShowTooltip'
SavedInstances\SavedInstances-@project-version@.lua:2679: in function `OnEnter'
ElvUI\Modules\datatexts\datatexts.lua:66: in function `onEnter'
ElvUI\Modules\datatexts\datatexts.lua:229: in function <ElvUI\Modules\datatexts\datatexts.lua:227>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:398
 localarr#categoryrow = <table> {
 }
 EnableModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:145
 RequestLockInfo = <function> defined @SavedInstances\SavedInstances.lua:2783
 localarr#blankrow = <table> {
 }
 TRADE_SKILL_LIST_UPDATE = <function> defined @SavedInstances\SavedInstances.lua:4890
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 IsEnabled = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:482
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:92
 DisableModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:381
 ADDON_LOADED = <function> defined @SavedInstances\SavedInstances.lua:2763
 RegisterMessage = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterBucketEvent = <function> defined @HandyNotes_DraenorTreasures\libs\AceBucket-3.0\AceBucket-3.0.lua:213
 memcheck = <function> defined @SavedInstances\SavedInstances.lua:3266
 scan_item_cds = <function> defined @SavedInstances\SavedInstances.lua:4784
 localarr#showcol = <table> {
 }
 SetEnabledState = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:468
 TradeSkillRescan = <function> defined @SavedInstances\SavedInstances.lua:4869
 CHAT_MSG_MONSTER_YELL = <function> defined @SavedInstances\SavedInstances.lua:2990
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @SavedInstances\SavedInstances.lua:2607
 NewModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:266
 GetModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:241
 ShowTooltip = <function> defined @SavedInstances\SavedInstances.lua:3724
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:170
 localarr#holidayinst = <table> {
 }
 localarr#instancerow = <table> {
 }
 RefreshMythicKeyInfo = <function> defined @SavedInstances\SavedInstances.lua:2846
 ScheduleRepeatingTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:127
 CancelAllTimers = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:158
 toonInit = <function> defined @SavedInstances\SavedInstances.lua:2592
 localarr#lfrbox = <table> {
 }
 GetName = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:310
 SetDefaultModuleState = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:418
 localarr#instancesaved = <table> {
 }
 localarr#categoryshown = <table> {
 }
 RefreshDailyWorldQuestInfo = <function> defined @SavedInstances\SavedInstances.lua:2924
 scale = 1
 RegisterBucketMessage = <function> defined @HandyNotes_DraenorTreasures\libs\AceBucket-3.0\AceBucket-3.0.lua:229
 orderedModules = <table> {
 }
 baseName = "SavedInstances"
 Disable = <function> defined @ElvUI\Libr

**Comment by ceylina** [comment]
You grabbed something wrong. 

Make sure you download the files from the code tab then copy the contents within the included Saved Instances folder ONLY.

**Comment by Akrolodoxis** [comment]
Yea I've done it this way... like always. But this time nothing works anymore
Doing everything as always

**Comment by gentoomaniac** [comment]
did you try deleting your addon saved variables? Might be the addon is choking on an unexpected value

kabbrev is loaded with a value from 
for toon, t in cpairs(vars.db.Toons, true) do
...
local kabbrev = KeystonetoAbbrev[t.MythicKey.name]

the last line i copied is the one reported for the crash

**Comment by Akrolodoxis** [comment]
I dont even have a char named Kabbrev...

**Comment by gentoomaniac** [comment]
I didn't say that ;p
The code is using a variable worth that name though and it gets filled with values from your saved variables (as far as I understand the code).
That however is causing the error.

So my guess is that your saved variables don't contain some values the code is expecting (and lacking error handling in case they don't exist). That causes a nil error.

By deleting the settings for SavedInstances you can för be it into default settings which might resolve your issue.
Do a backup of your WTF folder to easily restore them later in case it doesn't help

**Comment by Akrolodoxis** [comment]
Yep that fixed it, thanks
