### ISSUE TITLE
Reminder for Pet dungeon weekly

### ISSUE THREAD

**Issue by skmzarn** [eTzmNcbkrng/SavedInstances#20]
Would like to see specific weekly/daily quests in its column at all times, even if they are not completed, so they can act like reminders. Just like in the picture below:

http://i.imgur.com/HpWoXsn.jpg

The specific quests I would like to be added, would be these:

  [46292] = "Weekly", -- Pet Battle Challenge: Deadmines
  [45539] = "Weekly", -- Pet Battle Challenge: Wailing Caverns

I don't know how to make these appear at all times, which is what I want, but I guess their ids are correct from Wowhead, atleast.

**Comment by talar13** [comment]
I did this in my personal copy a long time ago...all you have to do to add it is to add...

  [46292] = "Weekly", --Pet Battle Challenge Dungeon Deadmines
  [45539] = "Weekly", --Pet Battle Challenge Dungeon Wailing Caverns

Under the section called local QuestExceptions right around line 329 in the current .lua file
