### ISSUE TITLE
Savedinstances2 is on curse

### ISSUE THREAD

**Issue by ceylina** [eTzmNcbkrng/SavedInstances#21]
https://mods.curse.com/addons/wow/272583-savedinstances2

Just got coremeeko2 to update with the latest changes with th is fork so SI is now available on curse again and this can be retired if that work.

Anyone coming here go to that page as the file is identical to this fork and is available for download/update from the curse client

**Comment by Stanzilla** [comment]
This will probably not be on Curse for long, considering the original code is all rights reserved.

**Comment by ceylina** [comment]
Did not notice that. Damn. Ok I will keep updating from github. I hope he comes back because this is getting annoying with the curse client constantly asking to update this.

**Comment by Stanzilla** [comment]
Right click => ignore. 😄

**Comment by ceylina** [comment]
But then I wont get notifications!

Joking aside I totally missed that license and agree that it should have been removed. Hopefully oscarucb didn't quit for good and will come back or someone will take over. There is nothing like this out there so I keep using it, hacked together and all.
