### ISSUE TITLE
7.3 Raid isn't tracked

### ISSUE THREAD

**Issue by yoshimo** [eTzmNcbkrng/SavedInstances#29]
When i kill bosses on the PTR in LFR, they show in the LFR window as killed, but SavedInstances won't show it.
What data is needed to add a complete new raid with its wings?

**Comment by Stanzilla** [comment]
The LFR ids, not sure where to find them atm though.

See https://github.com/eTzmNcbkrng/SavedInstances/blob/master/SavedInstances/SavedInstances.lua#L137

**Comment by yoshimo** [comment]
Can we iterate through the numbers from tod to maxidnand check for valid return values,aka brute force it?

**Comment by Stanzilla** [comment]
They are in LFGDungeons.dbc, do you still have your ID on the PTR to test something?

**Comment by yoshimo** [comment]
be fast, can go down any minute now:-)

**Comment by Stanzilla** [comment]
```
[1610] = { total=3, base=1, parent=1527, altid=nil, remap={ 1, 2, 3 } }, -- Antorus: Light's Breach
  [1611] = { total=3, base=4, parent=1527, altid=nil, remap={ 1, 2, 3 } }, -- Antorus: Forbidden Descent
  [1612] = { total=2, base=7, parent=1527, altid=nil, remap={ 1, 2 } }, -- Antorus: Hope's End
  [1613] = { total=1, base=9, parent=1527, altid=nil, remap={ 1 } }, -- Antorus: Seat of the Pantheon
```

still have to find what the parent id is

**Comment by yoshimo** [comment]
Is the parent the 8th or 10th return value from GetInstanceInfo maybe?

**Comment by Stanzilla** [comment]
it is but that gives the name, not the id

**Comment by yoshimo** [comment]
ID has been reset in anticipation of tomorrows patch on the ptr, so we won't be able to test it anyway.
![wowscrnshot_082617_132239](https://user-images.githubusercontent.com/17909/29793353-d1480b68-8c43-11e7-9c51-0b356f65e227.jpg)
is what i got during Varimathras

**Comment by Stanzilla** [comment]
alright, is the rest correct though? is it 2x3 bosses then 1x2 and then 1x1 like Tomb or is it a different split?

**Comment by Stanzilla** [comment]
Or maybe it was correct, I will use 1712 for now.

**Comment by yoshimo** [comment]
The third wing of 4 covers 3 bosses Varimathras, Kin'garoth and Shivarra, rest is invisible until it becomes available for a total of 11 bosses as it seems, so i would assume 3x3 and 1x2 in the last wing

**Comment by Stanzilla** [comment]
Thanks, we'll see how it goes when the wings open and everything is broken :D
