### ISSUE TITLE
Add Argus Emissaries to Saved Instance

### ISSUE THREAD

**Issue by talar13** [eTzmNcbkrng/SavedInstances#33]
Someone else posted on Curse to add Argus Emissaries to Saved Instance.  I took a quick look to see if I could help narrow down the problem instead of just giving you a problem to fix.

I think the problem is at line 2939 where it selects only Bountys for MapID(1014)... I think you are going to have to add the MapID for Argus.  I didn't have time to hunt down what that was so hopefully this at least gets you looking in the right direction.

I also noticed down at 2972 that that questID is not going to be flagged a lot on alts anymore...they changed it to not require that if the main has it.  Not sure what complications that could be causing (I haven't noticed any on my alts, but thought I would point it out since I noticed it).

**Comment by Stanzilla** [comment]
MapID 1014 is Dalaran
