### ISSUE TITLE
Possible micro stutter on 5 second timer? - possibly WORLD_MAP_UPDATE

### ISSUE THREAD

**Issue by ceylina** [eTzmNcbkrng/SavedInstances#4]
Did you add in a roughly 5 second timer into this edit? There seems to be a slight (for a brief like millisecond)  micro stutter on a 5 second interval in game with this version enabled.

I noticed I was having an ever so slight stuttering today while doing world quests on the broken shore. I went through pretty much all of my addons to see what was causing it and once I narrowed it down to saved instances, I was sure that it was causing the stuttering. I have tested sitting idle with only saved instances enabled and it indeed causes a slight delay every (roughly) 4-5 seconds

I will go through and see if you added some loop or timer to see if I can trace down what is causing this but it is definitely the modification of this addon that is the culprit.

**Comment by ceylina** [comment]
I may have found the culprit

line 2701 in SavedInstances.lua

self:RegisterEvent("WORLD_MAP_UPDATE", "RefreshDailyWorldQuestInfo")

I think registering based on WORLD_MAP_UPDATE is causing the stuttering as when I commented this out nad reloaded then logged out and back in to test, the stuttering went away. My guess is that in certain zones like the broken shores where the world map can update rapidly, it is causing it to trigger far too often.

Testing this for about 5 minutes on the broken shore, I have no stuttering disabling the registering of said event

**Comment by Stanzilla** [comment]
Uh, agree, `QUEST_LOG_UPDATE` should be good enough alone.

**Comment by eTzmNcbkrng** [comment]
Mistakenly closed by [332d225](https://github.com/eTzmNcbkrng/SavedInstances/commit/332d2251678653250d8bf2b17195508c3fa7a2a1), however seems to have been resolved by [5ac3d4e](https://github.com/eTzmNcbkrng/SavedInstances/commit/5ac3d4e16bea3f9b102128e86f9a578cb506c57a)
