### ISSUE TITLE
new instance "Siege of Triumvira"

### ISSUE THREAD

**Issue by oldboyz** [eTzmNcbkrng/SavedInstances#43]
hi

new dj "siege of Triumvira" is missing, having a mythic key of it make the addon crash

 **["siege of triumvira"] = L["SoT"]** is the easy part to add near the other dj abbreviation

then there is this code :
**local KeystoneAbbrev = {
  [197] = L["EoA"],
  [198] = L["DHT"],  ...
  [210] = L["CoS"],
  [227] = L["L Kara"],
  [233] = L["CoEN"]**

 > not sure which number allocate to SOT

**Comment by LordDeimos666** [comment]
Then you have an old version.
It's already fixed, so download the version from here: https://github.com/eTzmNcbkrng/SavedInstances/archive/master.zip

**Comment by dsabecky** [comment]
The ID is wrong in the current version (I have a pull request with proper ID)

**Comment by dsabecky** [comment]
This is fixed and should be marked as closed.
