### ISSUE TITLE
SavedInstancesDB = nil

### ISSUE THREAD

**Issue by Debuggernaut** [eTzmNcbkrng/SavedInstances#5]
Hey, I just downloaded the head as of today and tried it out for the first time ever, and it looks like the basic functionality of saving info about your characters is broken on my copy.  I always only see the current character anywhere in the GUI, and I noticed that nothing is getting saved in my WTF\account\---\SavedVariables\SavedInstances.lua file except "SavedInstancesDB = nil"

Anyone else seen this happen?

BTW, thanks for all the work you've done on this addon, it's looking great!

**Comment by Debuggernaut** [comment]
I narrowed it down to this commit, but I'm not sure what the actual problem is since I haven't really done any WoW UI stuff

commit 4697fbd3ad23136be9a1bcbe0c48606dae0b4cc1
Author: Benjamin Staneck <staneck@gmail.com>
Date:   Thu Apr 27 01:04:33 2017 +0200

    fix leaked globals and remove dead code

**Comment by Debuggernaut** [comment]
One more update:  I worked around the problem by checking out the last commit before the one I mentioned above, creating a database with that, then updating back to the HEAD, and I'm guessing this problem doesn't affect anyone who's already been using the addon

**Comment by eTzmNcbkrng** [comment]
This is particularly troubling because it would have only been presented to new user, have fixed it now so thanks @Debuggernaut for reporting.

**Comment by Stanzilla** [comment]
Oh, sorry.

**Comment by Debuggernaut** [comment]
Thanks guys!
