### ISSUE TITLE
Keybind doesn't work

### ISSUE THREAD

**Issue by angryindianman** [eTzmNcbkrng/SavedInstances#6]
thanks for updating this addon, excellent work. 
one minor problem.
I get this message when I press the addon keybind.

Message: [string "SAVEDINSTANCES"]:1: attempt to index global 'SavedInstances' (a nil value)
Time: 05/20/17 11:04:17
Count: 11
Stack: [C]: ?
[string "SAVEDINSTANCES"]:1: in function <[string "SAVEDINSTANCES"]:1>

I have little to no knowledge of coding but would really like to make this work. Please help me

**Comment by Stanzilla** [comment]
Fixed, sorry :(
