### ISSUE TITLE
Minimap icon missing

### ISSUE THREAD

**Issue by pquerner** [eTzmNcbkrng/SavedInstances#65]
Since some versions (I cannot remember) I am missing the minimap icon of this addon.

Tried the following:
completely delete Addon Folder and replaced it with master. (Restarted Game)

Using savedinstances current version (7.0.8 for wow 7.1.0) displays the icon just fine

I saw that in /libs folder theres loads of folders missing. Maybe thats fixed when this github release is cast onto curse some day, but not fixed if users simply download the current master as zip and want to start using it.

Dragging current master onto a from curse installed version (so lib folder keeps intact) works fine and displays minimap icon again.

**Comment by Stanzilla** [comment]
Try the alpha zip on wowace/curse, it has all it needs
