### ISSUE TITLE
CurseForge localization broken due to packager misbehaving

### ISSUE THREAD

**Issue by SacredDuckwhale** [eTzmNcbkrng/SavedInstances#68]
Users are already posting errors, see [here](https://www.wowace.com/projects/saved_instances/issues/300) and [here](https://mods.curse.com/addons/wow/saved_instances#c1058).

The CF packager has plenty of bugs that have been around for months, such as those reported [here](https://www.curseforge.com/forums/wow-sites/wow-sites-feedback/227726-big-problem-localization-substitution-syntax-and) and [here](https://www.curseforge.com/forums/wow-sites/wow-sites-feedback/203589-issues-with-localization-exporting-during-auto). There are likely others. One of those has caused the recent alpha build to break, because of multi-line phrases without a translation (as mentioned in the last link, point 2.)

I'm not sure if this can be fixed by setting handle-unlocalized, but since "blank" is the default behaviour, perhaps one of the alternatives works here:

* handle-unlocalized - what to do when you have an unlocalized string.

    if "english", then it will output the english value.
    if "comment", then it will output the english value, but comment it out the line.
    if "blank" (default), then it will output "", but comment out the line.
    if "ignore", then no line will be printed out.

**Comment by Stanzilla** [comment]
I think "english" is the best idea

**Comment by Stanzilla** [comment]
Did that now, latest alpha should be good.
